# Generated by Django 4.2 on 2023-08-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_customuser_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vwrfi',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
