# Generated by Django 4.2 on 2023-08-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_vwrfi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='vwrfi',
        ),
    ]
