# Generated by Django 4.2 on 2023-09-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_customuser_vwrfi'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('customer', 'customer'), ('Saler', 'Saler')], max_length=30, null=True),
        ),
    ]
