# Generated by Django 4.2 on 2023-09-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('customer', 'customer'), ('Saler', 'Saler'), ('delivery', 'delivery')], max_length=30, null=True),
        ),
    ]
