# Generated by Django 4.2 on 2023-07-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adrees', models.TextField(max_length=1000)),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
    ]
