# Generated by Django 4.2 on 2023-09-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo/')),
                ('call_us', models.CharField(max_length=20)),
                ('adreese', models.CharField(max_length=100)),
                ('emial_us', models.CharField(max_length=50)),
                ('facebook_link', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('twitter', models.CharField(max_length=200)),
                ('discord_link', models.CharField(max_length=200)),
            ],
        ),
    ]
