# Generated by Django 4.2 on 2023-09-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
