# Generated by Django 4.2 on 2023-07-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_alter_product_color_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
