# Generated by Django 4.2 on 2023-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='description',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
