# Generated by Django 4.2 on 2023-07-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
