# Generated by Django 4.2 on 2023-07-31 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_category_subcategory_alter_product_categore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Categore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category'),
        ),
    ]
