# Generated by Django 4.2 on 2023-07-31 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_product_categore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Categore',
        ),
    ]
