# Generated by Django 4.2 on 2023-07-31 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_product_categore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
