# Generated by Django 4.2 on 2023-07-31 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Categore',
        ),
    ]
