# Generated by Django 4.2 on 2023-07-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_brand_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='Brand',
            new_name='name',
        ),
    ]
