# Generated by Django 4.2 on 2023-08-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
