# Generated by Django 4.2 on 2023-08-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='SubCategory',
        ),
    ]
