# Generated by Django 4.2 on 2023-08-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
