# Generated by Django 4.2 on 2023-08-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_ofer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofer',
            name='image',
        ),
    ]
