# Generated by Django 4.2 on 2023-08-17 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_remove_ofer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='productimages/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='productimages/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='productimages/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='productimages/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='productimages/')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Product_images', to='shop.product')),
            ],
        ),
    ]
