# Generated by Django 4.2 on 2023-08-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_images',
            old_name='image1',
            new_name='images',
        ),
        migrations.RemoveField(
            model_name='product_images',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product_images',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product_images',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product_images',
            name='image5',
        ),
    ]
