# Generated by Django 4.2 on 2023-08-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_rename_image1_product_images_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Flag',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Sale', 'Sale'), ('Hot', 'Hot'), ('feature', 'feature')], max_length=30, null=True),
        ),
    ]
