# Generated by Django 4.2 on 2023-08-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
