# Generated by Django 4.2 on 2023-08-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
