# Generated by Django 4.2 on 2023-09-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Have_color',
            field=models.BooleanField(default=True),
        ),
    ]
